### ISSUE TITLE
enum 타입 재구현

### ISSUE THREAD

**Issue by JoSH0318** [cherrishRed/ios-rock-paper-scissors#8]
- rename
- 내부 case rawValue 개선 -> 키워드: [CustomStringConvertible](https://developer.apple.com/documentation/swift/customstringconvertible), 연산프로퍼티
- ErrorCase 제거
- 가위,바위,보 enum에 CaseIterable 프로토콜 상속 / allCases 활용한 element 생성 메서드 활용

**Comment by cherrishRed** [comment]
enum 에서 연산 프로퍼티를 만들 때, 연산 프로퍼티 자체가 하는 일은 함수와 같이 **'동작'** 을 하는 일인데, 함수의 이름을 동사로 시작하면 안되는 걸까요?

**Comment by cherrishRed** [comment]
enum 에서 연관값과 raw value 의 사용처는 어떻게 다른가요?
